export enum HTTP_STATUS {
    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NO_CONTENT = 204,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    PAYMENT_REQUIRED = 402,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    METHOD_NOT_ALLOWED = 405,
    NOT_ACCEPTABLE = 406,
    PROXY_AUTH_REQUIRED = 407,
    REQUEST_TIMEOUT = 408,
    CONFLICT = 409,
    GONE = 410,
    LENGTH_REQUIRED = 411,
    PRECONDITION_FAILED = 412,
    PAYLOAD_TOO_LARGE = 413,
    URI_TOO_LONG = 414,
    UNSUPPORTED_MEDIA_TYPE = 415,
    RANGE_NOT_SATISFIABLE = 416,
    EXPECTATION_FAILED = 417,
    IM_A_TEAPOT = 418,
    PAGE_EXPIRED = 419,
    MISDIRECTED_REQUEST = 421,
    UNPROCESSABLE_ENTITY = 422,
    LOCKED = 423,
    FAILED_DEPENDENCY = 424,
    UPGRADE_REQUIRED = 426,
    PRECONDITION_REQUIRED = 428,
    TOO_MANY_REQUESTS = 429,
    REQUEST_HEADER_TOO_LARGE = 431,
    LEGAL_REASONS = 451,
    INTERNAL_SERVER_ERROR = 500,
    NOT_IMPLEMENTED = 501,
    BAD_GATEWAY = 502,
    SERVICE_UNAVAILABLE = 503,
    GATEWAY_TIMEOUT = 504,
    HTTP_VERSION_NOT_SUPPORTED = 505,
    VARIANT_ALSO_NEGOTIATES = 506,
    INSUFFICIENT_STORAGE = 507,
    LOOP_DETECTED = 508,
    BANDWIDTH_LIMIT_EXCEEDED = 509,
    NOT_EXTENDED = 510,
    NETWORK_AUTH_REQUIRED = 511
}

export enum ACCOUNT_ROLE {
    ADMIN = 'ADMIN',
    MANAGER = 'MANAGER',
    SELLER = 'SELLER',
    EMPLOYEE = 'EMPLOYEE'
}

export enum PERMISSION {
    MANAGE_DASHBOARD = 'MANAGE_DASHBOARD',
    MANAGE_WAREHOUSE = 'MANAGE_WAREHOUSE',
    MANAGE_CONTENT = 'MANAGE_CONTENT',
    MANAGE_ACCOUNT = 'MANAGE_ACCOUNT',
    MANAGE_SALES = 'MANAGE_SALES',
    MANAGE_EMPLOYEE = 'MANAGE_EMPLOYEE',
}

export enum ORDER_STATUS {
    PENDING = 'PENDING',
    CANCELED = 'CANCELED',
    PREPARING = 'PREPARING',
    DELIVERING = 'DELIVERING',
    DONE = 'DONE'
}