export enum ACCOUNT_ROLE {
    ADMIN = 'ADMIN',
    MANAGER = 'MANAGER',
    SELLER = 'SELLER',
    EMPLOYEE = 'EMPLOYEE'
}

export enum PERMISSION {
    MANAGE_DASHBOARD = 'MANAGE_DASHBOARD',
    MANAGE_WAREHOUSE = 'MANAGE_WAREHOUSE',
    MANAGE_CONTENT = 'MANAGE_CONTENT',
    MANAGE_ACCOUNT = 'MANAGE_ACCOUNT',
    MANAGE_SALES = 'MANAGE_SALES',
    MANAGE_EMPLOYEE = 'MANAGE_EMPLOYEE',
}

export enum ORDER_STATUS {
    PENDING = 'PENDING',
    CANCELED = 'CANCELED',
    PREPARING = 'PREPARING',
    DELIVERING = 'DELIVERING',
    DONE = 'DONE'
}